require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - 'docs/styles/**/*'
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

RSpec/ExampleLength:
  Exclude:
    - 'spec/system/**/*'

RSpec/NestedGroups:
  Max: 5

Style/Documentation:
  Enabled: false
