require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - 'docs/styles/**/*'
  NewCops: enable

Style/Documentation:
  Enabled: false
