title: AsyncGo Documentation
url: "https://asyncgo.com/docs/"
exclude:
  - styles/
remote_theme: https://github.com/async-go/web-theme@main
markdown: kramdown
sass:
  style: compressed
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - sass
navigation:
  - title: Home
    url: /
  - title: Docs
    url: /docs/
  - title: Blog
    url: /blog
  - title: Hiring
    url: /hiring
  - title: Sign Up
    url: /index#signup
defaults:
  - scope:
      path: ""
    values:
      narrow: true
