title: AsyncGo Documentation
url: 'https://docs.asyncgo.com'
exclude:
  - styles/
remote_theme: https://github.com/async-go/web-theme@main
markdown: kramdown
sass:
    style: compressed
plugins:
  - jekyll-sitemap
  - sass
navigation:
  - title: Home
    url: https://asyncgo.com/
  - title: Docs
    url: /
  - title: Blog
    url: https://asyncgo.com/blog
  - title: Hiring
    url: https://asyncgo.com/hiring
  - title: Sign Up
    url: https://asyncgo.com/index#signup
defaults:
  - scope:
      path: ""
    values:
      narrow: true
