name: CI
on: push
jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.0.0'
      - uses: actions/cache@v2
        name: Cache yarn dependencies
        with:
          path: vendor/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: actions/cache@v2
        name: Cache bundler dependencies
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Install node dependencies
        run: bin/yarn install --production true --cache-folder vendor/yarn
      - name: Install bundler dependencies
        run: bundle install --without development production --jobs 4 --retry 3 --path vendor/bundle
      - name: Run rspec
        run: bundle exec rspec --tag ~type:system
  rspec-system:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.0.0'
      - uses: actions/cache@v2
        name: Cache yarn dependencies
        with:
          path: vendor/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: actions/cache@v2
        name: Cache bundler dependencies
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Install node dependencies
        run: bin/yarn install --production true --cache-folder vendor/yarn
      - name: Install bundler dependencies
        run: bundle install --without development production --jobs 4 --retry 3 --path vendor/bundle
      - name: Run rspec system specs
        run: bundle exec rspec --tag type:system
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.0.0'
      - uses: actions/cache@v2
        name: Cache bundler dependencies
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Install bundler dependencies
        run: bundle install --without development production --jobs 4 --retry 3 --path vendor/bundle
      - name: Run rubocop
        run: bundle exec rubocop
  haml-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.0.0'
      - uses: actions/cache@v2
        name: Cache bundler dependencies
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Install bundler dependencies
        run: bundle install --without development production --jobs 4 --retry 3 --path vendor/bundle
      - name: Run haml-lint
        run: bundle exec haml-lint
  standard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        name: Cache yarn dependencies
        with:
          path: vendor/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install node dependencies
        run: bin/yarn install --cache-folder vendor/yarn
      - name: Run standard
        run: bin/yarn exec standard
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        name: Cache yarn dependencies
        with:
          path: vendor/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install node dependencies
        run: bin/yarn install --cache-folder vendor/yarn
      - name: Run markdownlint
        run: bin/yarn exec markdownlint "*.md"
  vale:
    runs-on: ubuntu-latest
    container: jdkato/vale:v2.3.3
    steps:
      - uses: actions/checkout@v2
      - name: Run vale
        run: vale "*.md"
